title: "sprINT"

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
  - jemoji

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S2-CS2103T-T13-3/tp"
github_icon: "images/github-icon.png"

